force-app/main/default/objects/Author__c.object
<CustomObject>
    <label>Author</label>
    <nameField>
        <label>Author Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Authors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Book__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Author</label>
        <referenceTo>Author__c</referenceTo>
        <relationshipLabel>Books</relationshipLabel>
        <relationshipName>Books</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Book</label>
    <nameField>
        <label>Book Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Books</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recommendation__c.object
<CustomObject>
    <fields>
        <fullName>Book__c</fullName>
        <label>Book</label>
        <referenceTo>Book__c</referenceTo>
        <relationshipLabel>Recommendations</relationshipLabel>
        <relationshipName>Recommendations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rating__c</fullName>
        <label>Rating</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Review__c</fullName>
        <label>Review</label>
        <type>TextArea</type>
    </fields>
    <label>Recommendation</label>
    <nameField>
        <displayFormat>R-{0000}</displayFormat>
        <label>Recommendation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recommendations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/Books4EveryoneHomeController.cls
public with sharing class Books4EveryoneHomeController {
    
    /*QUERY for get books with name and description*/
  /*@AuraEnabled
      public static List<Book__c> getBooks(){
        return [SELECT Id,Name,Description__c
  						FROM Book__c];
      }*/
    
    /*QUERY for get books with name, description and author*/
  	@AuraEnabled
    public static List<Book__c> getBooksAndAuthor(){
        return [SELECT Id,Name, Description__c, Author__r.Name
               			FROM Book__c];
    }
    
    /*------------Create a INNER JOIN IN SOQL----------------*/
    @AuraEnabled
        public static List<Recommendation__c> getBookRecommendations(){
			return [SELECT Name, Review__c, Rating__c, Book__r.Name, Book__r.Author__r.Name
  							FROM Recommendation__c
  							WHERE Book__c != null];
    
        }
      
    
    /*------------Create a INNER RIGHT ANTI JOIN----------------*/
    @AuraEnabled
    public static List<Book__c> getBooksWithoutAuthors(){
        return [SELECT Name
               			FROM Book__c
               			Where Author__c = null];
    }
    
}