force-app/main/default/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of an item</description>
        <label>Line Item Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of an Item</description>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Small</fullName>
                </value>
                <value>
                    <fullName>Medium</fullName>
                </value>
                <value>
                    <fullName>Large</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>LIN-{00000}</displayFormat>
        <label>Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of a Product</description>
        <label>Line Item Description</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship__c</fullName>
        <label>Line Item</label>
        <referenceTo>Line_Item__c</referenceTo>
        <relationshipLabel>Product Line Items</relationshipLabel>
        <relationshipName>Product_Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of a product</description>
        <label>Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Product Line Item</label>
    <nameField>
        <displayFormat>LIN-{00000}</displayFormat>
        <label>Product Line Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Product Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/LineItemTriggerHandlerTest.cls
@isTest
public class LineItemTriggerHandlerTest {
	
    @isTest
    private static void TestInsertLineItem() {
        Line_Item__c var = new Line_Item__c(Description__c = 'Test',Type__c ='small');
        
        Test.startTest();
        insert var;
        Test.stopTest();
        
        Product_Line_Item__c pli = [select Id, Description__c, Type__c from Product_Line_Item__c where Relationship__c = : var.Id];
        System.assertEquals(pli.Description__c, var.Description__c,'Son Iguales');
    }
    
    
}